/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("MemProf");
gchar *s = N_("_Run...");
gchar *s = N_("Generate Profile");
gchar *s = N_("Generate Leak Info");
gchar *s = N_("Save Profile...");
gchar *s = N_("Save Leak Info...");
gchar *s = N_("Open File");
gchar *s = N_("Run");
gchar *s = N_("Profile");
gchar *s = N_("Leaks");
gchar *s = N_("Save File");
gchar *s = N_("Save");
gchar *s = N_("0k");
gchar *s = N_("32k");
gchar *s = N_("# of Allocations:");
gchar *s = N_("0");
gchar *s = N_("Bytes / Allocation:");
gchar *s = N_("0");
gchar *s = N_("Total Bytes:");
gchar *s = N_("0");
gchar *s = N_("Function");
gchar *s = N_("Self");
gchar *s = N_("Total");
gchar *s = N_("Children");
gchar *s = N_("Function");
gchar *s = N_("Bytes");
gchar *s = N_("Callers");
gchar *s = N_("Function");
gchar *s = N_("Bytes");
gchar *s = N_("Profile");
gchar *s = N_("Address");
gchar *s = N_("Size");
gchar *s = N_("Caller");
gchar *s = N_("Stack Trace");
gchar *s = N_("Function");
gchar *s = N_("Line");
gchar *s = N_("File");
gchar *s = N_("Leaks");
gchar *s = N_("Copyright Red Hat, Inc., 1999");
gchar *s = N_("Memory Profiling Tool");
gchar *s = N_("Functions to Skip:");
gchar *s = N_("label37");
gchar *s = N_("Add...");
gchar *s = N_("Delete");
gchar *s = N_("Defaults");
gchar *s = N_("Profile Options");
gchar *s = N_("Command to run on double click in stack trace:");
gchar *s = N_("Leak Detection Options");
gchar *s = N_("Adding Skip Function");
gchar *s = N_("Enter the name of a function to skip when computing  profiles");
gchar *s = N_("Add");
gchar *s = N_("Run Executable");
gchar *s = N_("Enter pathname to a executable");
gchar *s = N_("Run");
